version: '3'

services:
  kvstore-maven:
    container_name: kvstore-maven
    image: "docker-registry-priv.stefan-gabriel.com/kvstore-maven:latest"
    ports:
      - "26658:26658"
    networks:
      localnet:
        ipv4_address: 193.167.10.6

  node0:
    container_name: node0
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 193.167.10.2

  node1:
    container_name: node1
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 193.167.10.3

  node2:
    container_name: node2
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26661-26662:26656-26657"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 193.167.10.4

  node3:
    container_name: node3
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26663-26664:26656-26657"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 193.167.10.5

  nginx-tendermint:
    container_name: nginx-tendermint
    image: "docker-registry-priv.stefan-gabriel.com/nginx-tendermint:latest"
    ports:
      - "26665:26665"
    networks:
      localnet:
        ipv4_address: 193.167.10.7


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 193.167.10.0/16
