version: '3'

services:
  abci0:
    container_name: abci0
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/kvstore-maven:5"
    volumes:
      - /home/stefan/tendermint-data/abci0:/tendermint-data
    networks:
      localnet:
        ipv4_address: 193.167.10.8

  abci1:
    container_name: abci1
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/kvstore-maven:5"
    volumes:
      - /home/stefan/tendermint-data/abci1:/tendermint-data
    networks:
      localnet:
        ipv4_address: 193.167.10.9

  abci2:
    container_name: abci2
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/kvstore-maven:5"
    volumes:
      - /home/stefan/tendermint-data/abci2:/tendermint-data
    networks:
      localnet:
        ipv4_address: 193.167.10.10

  abci3:
    container_name: abci3
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/kvstore-maven:5"
    volumes:
      - /home/stefan/tendermint-data/abci3:/tendermint-data
    networks:
      localnet:
        ipv4_address: 193.167.10.10


  node0:
    container_name: node0
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci0:26658
    networks:
      localnet:
        ipv4_address: 193.167.10.2

  node1:
    container_name: node1
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci1:26658
    networks:
      localnet:
        ipv4_address: 193.167.10.3

  node2:
    container_name: node2
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26661-26662:26656-26657"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci2:26658
    networks:
      localnet:
        ipv4_address: 193.167.10.4

  node3:
    container_name: node3
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/tendermint/localnode:latest"
    ports:
      - "26663-26664:26656-26657"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    command: node --proxy_app=tcp://abci3:26658
    networks:
      localnet:
        ipv4_address: 193.167.10.5

  nginx-tendermint:
    container_name: nginx-tendermint
    restart: always
    image: "docker-registry-priv.stefan-gabriel.com/nginx-tendermint:latest"
    ports:
      - "26665:26665"
    networks:
      localnet:
        ipv4_address: 193.167.10.7


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 193.167.10.0/16
